"""
validation.py
-------------
Validation utility for microscopy background correction functions.

The module provides a single public function :func:`validate_correction`
which runs :func:`evaluate_spot_uniformity` from ``spot_uniformity.py``
over the full synthetic test suite and reports all failures at the end.

The script is compatible with suites generated by both ``bgcorrection_syn_img``
(numpy) and ``bgcorrection_syn_img_dask`` (Dask), since :func:`evaluate_spot_uniformity`
handles both array types transparently.
"""

from __future__ import annotations

from typing import Callable, Any
from acid.image_processing.bgcorrection_spot_uniformity import evaluate_spot_uniformity


def validate_correction(
    correction_fn: Callable,
    suite: dict[str, dict[str, Any]] | None = None,
    correction_kwargs: dict[str, Any] | None = None,
    suite_kwargs: dict[str, Any] | None = None,
) -> dict[str, dict[str, float]]:
    """
    Validate a correction function against the full synthetic test suite
    using the spot uniformity metric.

    For each background type in the suite, :func:`evaluate_spot_uniformity`
    is called to check whether the std of per-spot mean intensities decreases
    after correction. Failures are collected across all background types and
    reported together at the end via a single ``AssertionError``.

    Parameters
    ----------
    correction_fn : Callable
        Background correction function with the signature::

            corrected = correction_fn(observed, background, **correction_kwargs)

    suite : dict[str, dict[str, Any]] or None, optional
        Pre-built test suite as returned by ``build_test_suite()`` from
        either ``bgcorrection_syn_img`` or ``bgcorrection_syn_img_dask``. Must
        contain ``"observed"``, ``"background"``, and ``"mask"`` keys for
        each background type. When ``None``, the suite is generated
        automatically using
        ``bgcorrection_syn_img.build_test_suite(**suite_kwargs)``.
    correction_kwargs : dict[str, Any] or None, optional
        Keyword arguments forwarded to ``correction_fn``. Default is ``{}``.
    suite_kwargs : dict[str, Any] or None, optional
        Keyword arguments forwarded to ``build_test_suite()`` when ``suite``
        is ``None``. Default is ``{}``.

    Returns
    -------
    all_results : dict[str, dict[str, float]]
        Nested mapping ``{background_name: {"std_observed": float, "std_corrected": float}}``.
        Returned even when some assertions fail, so the caller can inspect
        numeric values for all background types.

    Raises
    ------
    AssertionError
        If spot uniformity does not improve for one or more background types,
        with a consolidated report of all failures.
    """
    if correction_kwargs is None:
        correction_kwargs = {}
    if suite_kwargs is None:
        suite_kwargs = {}

    if suite is None:
        from acid.image_processing.bgcorrection_syn_img import build_test_suite
        suite = build_test_suite(**suite_kwargs)

    all_results: dict[str, dict[str, float]] = {}
    failures: list[str] = []

    for bg_name, images in suite.items():
        try:
            results = evaluate_spot_uniformity(
                correction_fn=correction_fn,
                observed=images["observed"],
                background=images["background"],
                mask=images["mask"],
                correction_kwargs=correction_kwargs,
            )
            all_results[bg_name] = results
        except AssertionError as e:
            all_results[bg_name] = {"std_observed": float("nan"), "std_corrected": float("nan")}
            failures.append(f"  [{bg_name}] {e}")

    if failures:
        failure_report = "\n".join(failures)
        raise AssertionError(
            f"Validation failed for {len(failures)} background type(s):\n{failure_report}"
        )

    return all_results
