project_identity:
    project_name: "ACID"

## ==============================================
## ====    Stage 4. Background correction    ====
## ==============================================
background_correction:
    paths:
        fov_directory: "data/proc/fov"
        metadata_directory: "data/proc/proc_metadata"
        background_directory: "data/proc/background"
        output_directory: "data/proc/fov_proc"

    secondary_output:
        enabled: true
        directory: "secondary_output"

    runtime:
        enabled: true # Not used now
        verbose: true

    dataset_split:
        column: "is_train" #"dataset_split"
        labels:
            train: 1
            validation: 0
            test: 3

    background_function_selection:
        directory: ${background_correction.paths.background_directory}
        background_function_strategy: 1
        file_selection:
            filename: "default"
            include: ".ome.tif"
            exclude: null
            date_source: "modified_time"
            select: "newest"
            filename_date_separator: "_"
            filename_date_position: 0
            filename_date_format: "%Y%m%d"

    metadata:
        directory: ${background_correction.paths.metadata_directory}
        file_selection:
            filename: "default"
            include: ".csv"
            exclude:
                - "part_4b"
            date_source: "modified_time"
            select: "newest"
            filename_date_separator: "_"
            filename_date_position: 0
            filename_date_format: "%Y%m%d"

        dataframe_columns:
            fov_column_name: "ome_tif_file_name"
            well_column_name: "well"
            gridpos_column_name: "scene_name"
            null_value: .nan
            column_name_separator: "_"
            ch_name_separator: "-"
            illum_correct_df_date_clm_name: "illumination_correction_date"
            illum_correct_df_meta_date_format: "%y%m%d"
            illum_correct_df_file_name_clm_name: "illumination_correction_file_name"
            illum_correct_df_method_clm_name: "illumination_correction_method"
            illum_correct_df_offset_clm_name: "illumination_correction_offset"
            illum_correct_df_rescale_clm_name: "illumination_correction_rescale_background"
            illum_correct_df_clipping_clm_name: "illumination_correction_clip_output"
            illum_correct_df_clip_min_value_clm_name: "illumination_correction_min_clip_value"
            illum_correct_df_clip_max_value_clm_name: "illumination_correction_max_clip_value"
            illum_correct_df_offset_background_clm_name: "illumination_correction_offset_background"

        image_metadata:
            proc_img_meta_date_name: "processing_date_yymmdd"
            processing_date_format: "%y%m%d"
            proc_img_meta_dtype_name: "dtype"
            illum_corr_method_metadata_entry: "illumination_correction_method"
            illum_corr_offset_metadata_entry: "illumination_correction_offset"
            illum_corr_rescale_metadata_entry: "illumination_correction_rescale_background"
            illum_corr_clipping_metadata_entry: "illumination_correction_clipping"
            illum_corr_clip_min_value_metadata_entry: "illumination_correction_min_clip_value"
            illum_corr_clip_max_value_metadata_entry: "illumination_correction_max_clip_value"
            illum_corr_offset_background_metadata_entry: "illumination_correction_offset_background"

        saving:
            metadata_savingword: "metadata"
            metadata_file_suffix: "part_4b.csv"
            metadata_date_format: "%Y%m%d"
            save_file_name_separator: "_"
            save_csv_index: false

    processing:
        channel_axis: 0
        method: "division"
        offset: 400
        epsilon: 1.0e-8
        output_dtype: "float32"
        working_dtype: "float32"
        rescale_background: "max"
        clip_corrected_image: false
        min_clip_value: 0
        max_clip_value: null
        offset_background: true
        zero_kwargs: null
        verbose: false

    image_saving:
        directory: ${background_correction.paths.output_directory}
        photometric: "minisblack"
        save_imagej_compatible: true
        save_file_name_separator: "_"
        fov_illumin_corrected_savingword: "bg"
        ome_suffix: ".ome.tif"

    graphs_saving:
        save_graphs: true
        graph_saving_directory: "data/proc/plots"
        graph_date_format: "%Y%m%d"
        graph_suffix: ".png"
        graph_savingword: "illumination_correction"

## ==============================================
## ====    Stage 5. Object Segmentation      ====
## ==============================================
object_segmentation:
    paths:
        fov_directory: "data/proc/fov_proc"
        fov_background_corrected: "data/proc/fov_proc"
        metadata_directory: "data/proc/proc_metadata"
        output_directory: "data/proc/segmentation"

    secondary_output:
        enabled: true
        directory: "secondary_output"

    runtime:
        enabled: true # not used now
        verbose: true

    dataset_split:
        column: "is_train" #"dataset_split"
        labels:
            train: 1

            validation: 0
            test: 3

    metadata:
        directory: ${object_segmentation.paths.metadata_directory}

        file_selection:
            filename: "default"
            include: "part_4b.csv"
            exclude:
                - "part_5"
            date_source: "modified_time"
            select: "newest"
            filename_date_separator: "_"
            filename_date_position: 0
            filename_date_format: "%Y%m%d"

        segmentation_method_name: "cellpose"

        dataframe_columns:
            illum_correct_df_file_name_clm_name: illumination_correction_file_name
            null_value: .nan
            column_name_separator: "_"

            # Inherited from the stage before (stage 4)
            metadata_df_date_clm_name: segmentation_date
            metadata_df_file_name_clm_name: segmentation_file_name
            metadata_df_method_clm_name: segmentation_method
            metadata_df_method_version_clm_name: segmentation_method_version
            metadata_df_diameter_clm_name: ${object_segmentation.metadata.segmentation_method_name}${object_segmentation.metadata.dataframe_columns.column_name_separator}diameter
            metadata_df_flow_threshold_clm_name: ${object_segmentation.metadata.segmentation_method_name}${object_segmentation.metadata.dataframe_columns.column_name_separator}flow${object_segmentation.metadata.dataframe_columns.column_name_separator}threshold
            metadata_df_cellprob_threshold_clm_name: ${object_segmentation.metadata.segmentation_method_name}${object_segmentation.metadata.dataframe_columns.column_name_separator}cellprob${object_segmentation.metadata.dataframe_columns.column_name_separator}threshold
            metadata_df_downsampling_factor_clm_name: downsampling${object_segmentation.metadata.dataframe_columns.column_name_separator}factor
            metadata_df_nucleus_med_filter_size_name: nucleus${object_segmentation.metadata.dataframe_columns.column_name_separator}median${object_segmentation.metadata.dataframe_columns.column_name_separator}filter${object_segmentation.metadata.dataframe_columns.column_name_separator}size
            metadata_df_concactin_merge_med_filter_size_name: concactin${object_segmentation.metadata.dataframe_columns.column_name_separator}merge${object_segmentation.metadata.dataframe_columns.column_name_separator}median${object_segmentation.metadata.dataframe_columns.column_name_separator}filter${object_segmentation.metadata.dataframe_columns.column_name_separator}size
            metadata_df_resize_order_name: resize${object_segmentation.metadata.dataframe_columns.column_name_separator}order
            metadata_df_output_dtype_name: output${object_segmentation.metadata.dataframe_columns.column_name_separator}dtype
            metadata_df_meta_date_format: "%y%m%d"

        image_metadata:
            processing_date_format: "%y%m%d"

            preproc_img_meta_raw_file_name_entry: raw${object_segmentation.metadata.image_metadata.segmented_img_meta_separator}file${object_segmentation.metadata.image_metadata.segmented_img_meta_separator}name
            preproc_img_meta_scene_file_name_entry: scene${object_segmentation.metadata.image_metadata.segmented_img_meta_separator}file${object_segmentation.metadata.image_metadata.segmented_img_meta_separator}name
            preproc_img_meta_x_physic_px_size_entry: physical${object_segmentation.metadata.image_metadata.segmented_img_meta_separator}size${object_segmentation.metadata.image_metadata.segmented_img_meta_separator}x
            preproc_img_meta_y_physic_px_size_entry: physical${object_segmentation.metadata.image_metadata.segmented_img_meta_separator}size${object_segmentation.metadata.image_metadata.segmented_img_meta_separator}y
            preproc_img_meta_x_physic_px_size_unit_entry: physical${object_segmentation.metadata.image_metadata.segmented_img_meta_separator}size${object_segmentation.metadata.image_metadata.segmented_img_meta_separator}unit${object_segmentation.metadata.image_metadata.segmented_img_meta_separator}x
            preproc_img_meta_y_physic_px_size_unit_entry: physical${object_segmentation.metadata.image_metadata.segmented_img_meta_separator}size${object_segmentation.metadata.image_metadata.segmented_img_meta_separator}unit${object_segmentation.metadata.image_metadata.segmented_img_meta_separator}y

            segmented_img_meta_processing_steps: "median filter nuclei. merge concanavalin and actin by average intensity and median filter the result. downsample channels. stack channels together: pos-0-nuclei, pos-1-merge. cell segmentation. upsample segmentation mask to original size."
            segmented_img_meta_date_name: processing${object_segmentation.metadata.image_metadata.segmented_img_meta_separator}date${object_segmentation.metadata.image_metadata.segmented_img_meta_separator}yymmdd
            segmented_img_meta_method_name: "method"
            segmentation_method_version_name: "version"
            segmented_img_meta_diameter_name: ${object_segmentation.metadata.segmentation_method_name}${object_segmentation.metadata.image_metadata.segmented_img_meta_separator}diameter
            segmented_img_meta_flow_threshold_name: ${object_segmentation.metadata.segmentation_method_name}${object_segmentation.metadata.image_metadata.segmented_img_meta_separator}flow${object_segmentation.metadata.image_metadata.segmented_img_meta_separator}threshold
            segmented_img_meta_cellprob_threshold_name: ${object_segmentation.metadata.segmentation_method_name}${object_segmentation.metadata.image_metadata.segmented_img_meta_separator}cellprob${object_segmentation.metadata.image_metadata.segmented_img_meta_separator}threshold
            segmented_img_meta_downsampling_factor_name: downsampling${object_segmentation.metadata.image_metadata.segmented_img_meta_separator}factor
            segmented_img_meta_nucleus_med_filter_size_name: nucleus${object_segmentation.metadata.image_metadata.segmented_img_meta_separator}median${object_segmentation.metadata.image_metadata.segmented_img_meta_separator}filter${object_segmentation.metadata.image_metadata.segmented_img_meta_separator}size
            segmented_img_meta_concactin_merge_med_filter_size_name: concanavalin${object_segmentation.metadata.image_metadata.segmented_img_meta_separator}actin${object_segmentation.metadata.image_metadata.segmented_img_meta_separator}merge${object_segmentation.metadata.image_metadata.segmented_img_meta_separator}median${object_segmentation.metadata.image_metadata.segmented_img_meta_separator}filter${object_segmentation.metadata.image_metadata.segmented_img_meta_separator}size
            segmented_img_meta_resize_order_name: upsampling${object_segmentation.metadata.image_metadata.segmented_img_meta_separator}resize${object_segmentation.metadata.image_metadata.segmented_img_meta_separator}order
            segmented_img_meta_processing_name: processing${object_segmentation.metadata.image_metadata.segmented_img_meta_separator}steps
            segmented_img_meta_dtype_name: "dtype"
            segmented_img_meta_separator: "_"

        saving:
            metadata_savingword: metadata
            metadata_file_suffix: part${object_segmentation.metadata.saving.save_file_name_separator}5.csv
            metadata_date_format: "%Y%m%d"
            save_file_name_separator: "_"
            save_csv_index: False

    processing:
        model_backend: "cellpose"
        output_dtype: uint16

        # set parameters 1: preprocessing
        channel_axis: 0
        nucleus_position: 0
        concanavalin_position: 1
        actin_position: 2
        med_filter_nucleus: 3
        med_filter_concactin_merge: 3
        downsampling_factor: 2

        # set parameters 2: model eval/predict/segment
        flow_threshold: 0.4
        cellprob_threshold: 0.0
        diameter: 75

        # set parameters 3. Resizing masks
        order: 0
        preserve_range: True
        anti_aliasing: False

    image_saving:
        photometric: "minisblack"
        save_imagej_compatible: True
        save_file_name_separator: "_"
        segmentation_savingword: segmentation
        ome_suffix: ".ome.tif"

## ==============================================
## ====    Stage 6. Feature extraction       ====
## ==============================================
feature_extraction:
    paths:
        fov_directory: "data/proc/fov_proc"
        segmentation_directory: "data/proc/segmentation"
        metadata_directory: "data/proc/proc_metadata"
        output_directory: "data/proc/measurement"

    secondary_output:
        enabled: true
        directory: "secondary_output"

    metadata:
        directory: ${feature_extraction.paths.metadata_directory}

        file_selection:
            filename: "default"
            include: "csv"
            exclude:
                - "part_6"
            date_source: "modified_time"
            select: "newest"
            filename_date_separator: "_"
            filename_date_position: 0
            filename_date_format: "%Y%m%d"

        dataframe_columns:
            null_value: .nan
            fov_column_name: "illumination_correction_file_name"
            segmentation_column_name: "segmentation_file_name"
            metadata_df_meta_date_format: "%y%m%d"
            metadata_df_date_clm_name: "features_extraction_date"
            metadata_df_file_name_clm_name: "features_data_frame"
            metadata_df_method_clm_name: "features_extraction_preprocessing"
            preprocessing_steps: "move channel axis to last position; gaussian smoothing with sigma 3 along last axis; exclude labels touching image edge"

        saving:
            save_file_name_separator: "_"
            metadata_savingword: "metadata"
            metadata_file_suffix: "part_6.csv"
            metadata_date_format: "%Y%m%d"
            save_csv_index: false

    processing:
        channel_axis: 0
        sigma: 3
        axes: -1

    features_saving:
        ome_suffix: ".ome.tif"
        output_suffix: ".csv"
        save_csv_index: false
