
## NEW
input_field_of_view:
    fov_directory : "data/proc/fov"


## Edwin proposal
output:
    directory: "data/proc/fov_proc"
    secondary:
        enabled: true
        directory: "secondary_output"

    dtype: "float32"

metadata:
    directory: "data/proc/proc_metadata"
    filename: "default"

    default_selection:
        include: ".csv"
        exclude:
            - "part_4b"
        date_source: "modified_time"
        select: "newest"
        filename_date_separator: "_"
        filename_date_position: 0
        filename_date_format: "%Y%m%d"

    dataset_split:
        column: "is_train" #"dataset_split"
        labels:
            train: 1
            validation: 0
            test: 3

background_correction:
    directory: "data/proc/background"
    filename: "default"

    default_selection:
        include: ".ome.tif"
        exclude: null

    strategies:
        dataset: 1
        well: 2
        grid_position: 3

    null_value: .nan

    column_name_separator: "_"

    background_function_strategy: 1
    background_function_timestamp: "default"
    background_from_file_name: False
    background_default_separator: "_"
    background_default_date_position: 0
    background_default_date_format: "%Y%m%d"
    background_default_reverse: True

    illum_corr_method_metadata_entry: illumination_correction_method
    illum_corr_offset_metadata_entry: illumination_correction_offset
    illum_corr_rescale_metadata_entry: illumination_correction_rescale_background
    illum_corr_clipping_metadata_entry: illumination_correction_clipping
    illum_corr_clip_min_value_metadata_entry: illumination_correction_min_clip_value
    illum_corr_clip_max_value_metadata_entry: illumination_correction_max_clip_value
    illum_corr_offset_background_metadata_entry: illumination_correction_offset_background

    illum_correct_df_date_clm_name: "illumination_correction_date"
    illum_correct_df_file_name_clm_name: "illumination_correction_file_name"
    illum_correct_df_method_clm_name: "illumination_correction_method"
    illum_correct_df_offset_clm_name: "illumination_correction_offset"
    illum_correct_df_rescale_clm_name: "illumination_correction_rescale_background"
    illum_correct_df_clipping_clm_name: "illumination_correction_clip_output"
    illum_correct_df_clip_min_value_clm_name: "illumination_correction_min_clip_value"
    illum_correct_df_clip_max_value_clm_name: "illumination_correction_max_clip_value"
    illum_correct_df_offset_background_clm_name: "illumination_correction_offset_background"
    illum_correct_df_meta_date_format: "%y%m%d"


    fov_directory: "data/proc/fov"
    fov_column_name : "ome_tif_file_name"

    proc_img_meta_date_name: "processing_date_yymmdd"
    proc_img_meta_dtype_name: "dtype"
    processing_date_format: "%y%m%d"

    output_dtype: "float32"
    method: "division"
    offset: 400
    rescale_background: "max"
    clip_corrected_image: false
    min_clip_value: 0
    max_clip_value: null
    offset_background: true

    channel_axis: 0
    epsilon: 1.0e-8
    working_dtype: "float32"
    zero_kwargs: null
    verbose: true

    ome_suffix: ".ome.tif"
    save_file_name_separator: "_"
    fov_illumin_corrected_savingword: "bg"
    output_directory: "data/proc/fov_proc"
    save_imagej_compatible: true
    photometric: "minisblack"



# =============================================================================
# INPUT FIELD-OF-VIEW CONFIGURATION
# =============================================================================


gridpos_column_name: "scene_name"
well_column_name: "well"

# =============================================================================
# GENERAL PROCESSING METADATA
# =============================================================================
#output_dtype: "float32"
#null_value: .nan
#proc_img_meta_date_name: "processing_date_yymmdd"
#proc_img_meta_dtype_name: "dtype"
#processing_date_format: "%y%m%d"

# =============================================================================
# ILLUMINATION CORRECTION IMAGE METADATA ENTRIES
# =============================================================================
#illum_corr_method_metadata_entry: "illumination_correction_method"
#illum_corr_offset_metadata_entry: "illumination_correction_offset"
#illum_corr_rescale_metadata_entry: "illumination_correction_rescale_background"
#illum_corr_clipping_metadata_entry: "illumination_correction_clipping"
#illum_corr_clip_min_value_metadata_entry: "illumination_correction_min_clip_value"
#illum_corr_clip_max_value_metadata_entry: "illumination_correction_max_clip_value"
#illum_corr_offset_background_metadata_entry: "illumination_correction_offset_background"


# =============================================================================
# ILLUMINATION CORRECTION METHOD PARAMETERS
# =============================================================================
#background_function_strategy: 1
#method: "division"
#offset: 400
#rescale_background: "max"
#clip_corrected_image: false
#min_clip_value: 0
#max_clip_value: null
#offset_background: true

# =============================================================================
# BACKGROUND CORRECTION ARRAY / NUMERICAL PARAMETERS
# =============================================================================
#channel_axis: 0
#epsilon: 1.0e-8
#working_dtype: "float32"
#zero_kwargs: null
#verbose: true

# =============================================================================
# OUTPUT IMAGE FILE NAMING AND SAVING
# =============================================================================
#ome_suffix: ".ome.tif"
#save_file_name_separator: "_"
#fov_illumin_corrected_savingword: "bg"
#output_directory: "data/proc/fov_proc"
#save_imagej_compatible: true
#photometric: "minisblack"


# =============================================================================
# METADATA DATAFRAME COLUMN NAMING
# =============================================================================
column_name_separator: "_"
#illum_correct_df_date_clm_name: "illumination_correction_date"
#illum_correct_df_file_name_clm_name: "illumination_correction_file_name"
#illum_correct_df_method_clm_name: "illumination_correction_method"
#illum_correct_df_offset_clm_name: "illumination_correction_offset"
#illum_correct_df_rescale_clm_name: "illumination_correction_rescale_background"
#illum_correct_df_clipping_clm_name: "illumination_correction_clip_output"
#illum_correct_df_clip_min_value_clm_name: "illumination_correction_min_clip_value"
#illum_correct_df_clip_max_value_clm_name: "illumination_correction_max_clip_value"
#illum_correct_df_offset_background_clm_name: "illumination_correction_offset_background"



# =============================================================================
# METADATA DATAFRAME FILE SAVING
# =============================================================================
#illum_correct_df_meta_date_format: "%y%m%d"
metadata_directory: "data/proc/proc_metadata"
metadata_date_format: "%Y%m%d"
project_name: "ACID"
metadata_savingword: "metadata"
save_csv_index: false
metadata_file_suffix: "part_4b.csv"
